/*
 *   Apache License 2.0
 *
 *   Copyright (c) 2024, Mattias Aabmets
 *
 *   The contents of this file are subject to the terms and conditions defined in the License.
 *   You may not use, modify, or distribute this file except in compliance with the License.
 *
 *   SPDX-License-Identifier: Apache-2.0
 */

import fsp from "node:fs/promises";
import path from "node:path";
import { ipcAutomation } from "@src/automation.js";
import { findStaleOutputs } from "@src/check.js";
import { LEGACY_NOTICE_PREFIX } from "@src/output-files.js";
import { toPosix } from "@src/utils.js";
import { fixtures } from "@testutils/fixture-tracker.js";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

const MAIN_ONLY = `import { defineChannels, send } from "automate-electron-ipc";

export default defineChannels({
   ping: send<() => void>(),
});
`;

/** Whether the file exists. */
const exists = (file: string) =>
   fsp.access(file).then(
      () => true,
      () => false,
   );

describe("stale generated files", () => {
   beforeEach(() => {
      vi.spyOn(console, "warn").mockImplementation(() => undefined);
   });
   afterEach(() => {
      vi.restoreAllMocks();
   });

   /** Runs the fixture, then runs it again with the schema replaced by `schema`. */
   async function rerun(fixture: string, schema: string | ((source: string) => string)) {
      const project = await fixtures.run(fixture);
      const dir = path.join(project.dir, project.ipcDataDir);
      const schemaFile = path.join(dir, "schema.ts");
      const source = await fsp.readFile(schemaFile, "utf8");
      await fsp.writeFile(schemaFile, typeof schema === "string" ? schema : schema(source));
      return { project, dir, listed: () => fsp.readdir(dir).then((names) => names.sort()) };
   }

   it("removes utility.ts when the last utility channel is gone", async () => {
      const { project, dir, listed } = await rerun("electron-utility", MAIN_ONLY);
      expect(await listed()).toContain("utility.ts");
      expect(await findStaleOutputs({ cwd: project.dir })).toContain(
         toPosix(path.join(dir, "utility.ts")),
      );

      await ipcAutomation(project.dir);

      expect(await listed()).not.toContain("utility.ts");
      expect(await findStaleOutputs({ cwd: project.dir })).toEqual([]);
   });

   it("removes both service worker files when the last service worker channel is gone", async () => {
      const { project, listed } = await rerun("electron-service-worker", MAIN_ONLY);
      expect(await listed()).toEqual(
         expect.arrayContaining(["service-worker-preload.ts", "service-worker.d.ts"]),
      );

      await ipcAutomation(project.dir);

      const names = await listed();
      expect(names).not.toContain("service-worker-preload.ts");
      expect(names).not.toContain("service-worker.d.ts");
      expect(names).toEqual(expect.arrayContaining(["main.ts", "preload.ts", "window.d.ts"]));
   });

   it("removes the files of a scope that the schema no longer has", async () => {
      const { project, listed } = await rerun("electron-scopes", (source) =>
         source
            .replaceAll('"settings", "editor"', '"editor"')
            .replaceAll('["settings"', '["editor"'),
      );
      expect(await listed()).toEqual(
         expect.arrayContaining(["preload.settings.ts", "window.settings.d.ts"]),
      );

      await ipcAutomation(project.dir);

      const names = await listed();
      expect(names).not.toContain("preload.settings.ts");
      expect(names).not.toContain("window.settings.d.ts");
      expect(names).toEqual(expect.arrayContaining(["preload.editor.ts", "window.editor.d.ts"]));
   });

   it("keeps a file without the header, and removes one with the old notice", async () => {
      const { project, dir, listed } = await rerun("electron-scopes", MAIN_ONLY);
      await fsp.writeFile(path.join(dir, "preload.foo.ts"), "export const mine = 1;\n");
      await fsp.writeFile(path.join(dir, "window.foo.d.ts"), "// Generated by hand\n");
      await fsp.writeFile(
         path.join(dir, "preload.bar.ts"),
         `${LEGACY_NOTICE_PREFIX}\n// ANY CHANGES TO THIS FILE WILL NOT PERSIST BETWEEN GENERATIONS.\n`,
      );

      await ipcAutomation(project.dir);

      const names = await listed();
      expect(names).toContain("preload.foo.ts");
      expect(names).toContain("window.foo.d.ts");
      expect(names).not.toContain("preload.bar.ts");
      expect(await fsp.readFile(path.join(dir, "preload.foo.ts"), "utf8")).toBe(
         "export const mine = 1;\n",
      );
   });

   it("lists a stale file before the run, and nothing after it", async () => {
      const { project, dir } = await rerun("electron-utility", MAIN_ONLY);
      const utility = toPosix(path.join(dir, "utility.ts"));
      expect(await findStaleOutputs({ cwd: project.dir })).toEqual(
         expect.arrayContaining([utility]),
      );

      await ipcAutomation(project.dir);

      expect(await exists(utility)).toBe(false);
      expect(await findStaleOutputs({ cwd: project.dir })).toEqual([]);
   });

   it("does nothing to a project that has no stale files", async () => {
      const project = await fixtures.run("electron-scopes");
      const dir = path.join(project.dir, project.ipcDataDir);
      const before = (await fsp.readdir(dir)).sort();

      await ipcAutomation(project.dir);

      expect((await fsp.readdir(dir)).sort()).toEqual(before);
   });
});
