/*
 *   Apache License 2.0
 *
 *   Copyright (c) 2024, Mattias Aabmets
 *
 *   The contents of this file are subject to the terms and conditions defined in the License.
 *   You may not use, modify, or distribute this file except in compliance with the License.
 *
 *   SPDX-License-Identifier: Apache-2.0
 */

/** Words that cannot be the name of a variable, which `window.d.ts` declares the API as. */
const RESERVED_WORDS = [
   "arguments",
   "await",
   "break",
   "case",
   "catch",
   "class",
   "const",
   "continue",
   "debugger",
   "default",
   "delete",
   "do",
   "else",
   "enum",
   "eval",
   "export",
   "extends",
   "false",
   "finally",
   "for",
   "function",
   "if",
   "implements",
   "import",
   "in",
   "instanceof",
   "interface",
   "let",
   "new",
   "null",
   "package",
   "private",
   "protected",
   "public",
   "return",
   "static",
   "super",
   "switch",
   "this",
   "throw",
   "true",
   "try",
   "typeof",
   "var",
   "void",
   "while",
   "with",
   "yield",
];

/**
 * Properties of `window` and `globalThis` that a page, the browser or Node already has. The
 * exposed API would replace or hide them, or `contextBridge` would refuse to define it.
 */
const WELL_KNOWN_GLOBALS = [
   // The own properties of `window` that scripts commonly use.
   "alert",
   "blur",
   "caches",
   "cancelAnimationFrame",
   "clearInterval",
   "clearTimeout",
   "close",
   "closed",
   "confirm",
   "console",
   "createImageBitmap",
   "crypto",
   "customElements",
   "devicePixelRatio",
   "document",
   "event",
   "external",
   "fetch",
   "find",
   "focus",
   "frameElement",
   "frames",
   "getComputedStyle",
   "getSelection",
   "history",
   "indexedDB",
   "innerHeight",
   "innerWidth",
   "isSecureContext",
   "length",
   "localStorage",
   "location",
   "locationbar",
   "matchMedia",
   "menubar",
   "moveBy",
   "moveTo",
   "name",
   "navigator",
   "onerror",
   "onload",
   "onmessage",
   "open",
   "opener",
   "origin",
   "outerHeight",
   "outerWidth",
   "parent",
   "performance",
   "personalbar",
   "postMessage",
   "print",
   "prompt",
   "queueMicrotask",
   "requestAnimationFrame",
   "requestIdleCallback",
   "resizeBy",
   "resizeTo",
   "screen",
   "screenX",
   "screenY",
   "scroll",
   "scrollBy",
   "scrollTo",
   "scrollX",
   "scrollY",
   "scrollbars",
   "self",
   "sessionStorage",
   "setInterval",
   "setTimeout",
   "status",
   "statusbar",
   "stop",
   "structuredClone",
   "toolbar",
   "top",
   "window",
   // The globals of the language.
   "Array",
   "ArrayBuffer",
   "BigInt",
   "Boolean",
   "DataView",
   "Date",
   "Error",
   "Function",
   "Infinity",
   "Intl",
   "JSON",
   "Map",
   "Math",
   "NaN",
   "Number",
   "Object",
   "Promise",
   "Proxy",
   "Reflect",
   "RegExp",
   "Set",
   "String",
   "Symbol",
   "WeakMap",
   "WeakSet",
   "decodeURI",
   "decodeURIComponent",
   "encodeURI",
   "encodeURIComponent",
   "globalThis",
   "isFinite",
   "isNaN",
   "parseFloat",
   "parseInt",
   "undefined",
   // What the preload script and the sandbox of Electron provide.
   "Buffer",
   "electron",
   "exports",
   "global",
   "module",
   "process",
   "require",
];

const RESERVED_NAMES: ReadonlySet<string> = new Set([...RESERVED_WORDS, ...WELL_KNOWN_GLOBALS]);

/** Whether the name is a reserved word, or a global that the exposed API must not hide. */
export function isReservedGlobalName(name: string): boolean {
   return RESERVED_NAMES.has(name);
}

export default { isReservedGlobalName };
