/*
 *   Apache License 2.0
 *
 *   Copyright (c) 2024, Mattias Aabmets
 *
 *   The contents of this file are subject to the terms and conditions defined in the License.
 *   You may not use, modify, or distribute this file except in compliance with the License.
 *
 *   SPDX-License-Identifier: Apache-2.0
 */

import fsp from "node:fs/promises";
import path from "node:path";
import type * as t from "@types";
import utils from "./utils.js";

/** The start of the first line of the header of every generated file. */
export const GENERATED_PREFIX = "// Generated by ipcgen";
/** The first line of the notice that earlier versions wrote, whose files are still ours. */
export const LEGACY_NOTICE_PREFIX = "// NOTICE: THIS FILE WAS GENERATED BY AUTOMATE-ELECTRON-IPC.";

/**
 * The header at the top of every generated file. It names the schema, relative to the project root
 * with `/` separators, and keeps ESLint and Biome from linting or reformatting the file.
 */
export function notice(config: t.IPCResolvedConfig): string {
   const schemaPath = config.ipcSchema
      ? utils.toPosix(path.relative(config.projectRoot, config.ipcSchema.path))
      : "the schema";
   return [
      `${GENERATED_PREFIX} (automate-electron-ipc) from ${schemaPath}. Do not edit.`,
      "/* eslint-disable */",
      "// biome-ignore-all lint: generated file",
      "// biome-ignore-all assist: generated file",
      "// biome-ignore-all format: generated file",
   ].join("\n");
}

/** Writes the files, after making the directory of each. */
export async function writeOutputs(outputs: t.OutputFile[]): Promise<void> {
   await Promise.all(
      outputs.map(async (output) => {
         await fsp.mkdir(path.dirname(output.path), { recursive: true });
         await fsp.writeFile(output.path, output.contents);
      }),
   );
}
