/*
 *   Apache License 2.0
 *
 *   Copyright (c) 2024, Mattias Aabmets
 *
 *   The contents of this file are subject to the terms and conditions defined in the License.
 *   You may not use, modify, or distribute this file except in compliance with the License.
 *
 *   SPDX-License-Identifier: Apache-2.0
 */

import fsp from "node:fs/promises";
import path from "node:path";
import type * as t from "@types";

/** The notice at the top of every generated file. */
export const NOTICE = [
   "// NOTICE: THIS FILE WAS GENERATED BY AUTOMATE-ELECTRON-IPC.",
   "// ANY CHANGES TO THIS FILE WILL NOT PERSIST BETWEEN GENERATIONS.",
].join("\n");

/** Writes the files, after making the directory of each. */
export async function writeOutputs(outputs: t.OutputFile[]): Promise<void> {
   await Promise.all(
      outputs.map(async (output) => {
         await fsp.mkdir(path.dirname(output.path), { recursive: true });
         await fsp.writeFile(output.path, output.contents);
      }),
   );
}
