/*
 *   Apache License 2.0
 *
 *   Copyright (c) 2024, Mattias Aabmets
 *
 *   The contents of this file are subject to the terms and conditions defined in the License.
 *   You may not use, modify, or distribute this file except in compliance with the License.
 *
 *   SPDX-License-Identifier: Apache-2.0
 */

import fsp from "node:fs/promises";
import path from "node:path";
import type * as t from "@types";
import { type Scope, scopedFilePath } from "../scopes.js";
import utils from "../utils.js";
import { ImportsGenerator } from "./imports-generator.js";
import { getOriginalParams } from "./param-names.js";
import { renameChannelSpecs } from "./rename-signatures.js";

/** The `maxQueue` of a port channel which does not set it: how many messages a send queue holds. */
const DEFAULT_MAX_QUEUE = 1000;
/** The `highWaterMark` of a stream which does not set it: how many chunks the page may not have read. */
const DEFAULT_HIGH_WATER_MARK = 1024;

export class BaseWriter {
   protected config: t.IPCResolvedConfig;
   protected pfsArray: t.ParsedFileSpecs[];
   /**
    * The scope that the file is written for. The writers of the files of a page are given the
    * channels of the surface of the scope only, and write their file next to the one of the
    * surface of no scope, which is `null`.
    */
   protected scope: Scope;
   protected importsGenerator: ImportsGenerator;
   protected indents: string[];
   protected notice = [
      "// NOTICE: THIS FILE WAS GENERATED BY AUTOMATE-ELECTRON-IPC.",
      "// ANY CHANGES TO THIS FILE WILL NOT PERSIST BETWEEN GENERATIONS.",
   ].join("\n");

   public constructor(
      config: t.IPCResolvedConfig,
      pfsArray: t.ParsedFileSpecs[],
      scope: Scope = null,
   ) {
      if (this.constructor === BaseWriter) {
         throw new Error(`Cannot instantiate abstract base class '${this.constructor.name}'`);
      }
      this.config = config;
      this.pfsArray = pfsArray;
      this.scope = scope;
      this.importsGenerator = new ImportsGenerator(
         config.projectUsesNodeNext,
         this.getTargetFilePath(),
         this.getReservedNames(),
      );
      this.indents = this.getCodeIndents();
   }

   private throwAbstractError(methodName: string): void {
      throw new Error(`Must implement method '${methodName}' in '${this.constructor.name}' class`);
   }

   protected getTargetFilePath(): string {
      this.throwAbstractError("getTargetFilePath");
      return null as unknown as string;
   }

   /** The path of the file of a page for the scope, such as `preload.settings.ts` for `preload.ts`. */
   protected getScopedFilePath(filePath: string): string {
      return scopedFilePath(filePath, this.scope);
   }

   /** The names that the generated file declares or imports, which schema types must not take. */
   protected getReservedNames(): string[] {
      return [];
   }

   /** Whether the file has nothing to declare, which is written as the empty file. */
   protected isEmpty(): boolean {
      return this.pfsArray.length === 0;
   }

   protected renderEmptyFileContents(): string {
      this.throwAbstractError("renderEmptyFileContents");
      return null as unknown as string;
   }

   protected renderFileContents(): string {
      this.throwAbstractError("generateFileContents");
      return null as unknown as string;
   }

   /**
    * The channel name that Electron sees, as a quoted literal: the name of the channel in the
    * schema behind `channelPrefix`. Hooks and errors keep the name from the schema. `suffix` names
    * a second wire channel of the same schema channel, such as `:reply`. A schema channel name is
    * an identifier, so a name with a colon cannot be the wire name of another channel.
    */
   protected wireName(name: string, suffix = ""): string {
      return `'${this.config.channelPrefix ?? ""}${name}${suffix}'`;
   }

   /** The name that the API is exposed as in the page. */
   protected getExposeAs(): string {
      return this.config.exposeAs ?? "ipc";
   }

   /** Whether the preload script exposes the API itself, as it loads. */
   protected getAutoExpose(): boolean {
      return this.config.autoExpose ?? true;
   }

   /** Whether the API of the page has the `getPathForFile` helper. */
   protected getPathForFileEnabled(): boolean {
      return this.config.getPathForFile ?? false;
   }

   /**
    * The time after which a call of a channel is rejected: the option of the channel, or else the
    * default of the config. `0` means no timeout. The default does not apply to a stream, which
    * times out only through its own option.
    */
   protected getTimeoutMs(spec: t.ChannelSpec): number {
      if (spec.kind === "Stream") {
         return spec.timeoutMs ?? 0;
      }
      return spec.timeoutMs ?? this.config.timeoutMs ?? 0;
   }

   /** `, <ms>` for the last argument of a call with a timeout, and nothing for one without. */
   protected getTimeoutArgument(spec: t.ChannelSpec): string {
      const timeoutMs = this.getTimeoutMs(spec);
      return timeoutMs > 0 ? `, ${timeoutMs}` : "";
   }

   /**
    * Whether the files serialize what the channels carry, when the config names a serializer.
    */
   protected usesSerializer(): boolean {
      return !!this.config.serializer;
   }

   /**
    * Whether the messages of the channel go through the serializer: the arguments and the results of
    * `invoke`, `send`, `stream`, `emit` and `ask`, the messages of a `port` or `mainPort` channel,
    * which travel as one value, the list of the arguments, and the calls, sends, results and chunks
    * of the channels with a utility process, and the calls, sends, questions and answers of the
    * channels with a service worker. A writer that only pairs the ends of a channel, and sees none
    * of its messages, turns the channel off for its file.
    */
   protected isSerializedSpec(spec: t.ChannelSpec): boolean {
      return (
         this.usesSerializer() &&
         (spec.direction === "RendererToMain" ||
            spec.direction === "MainToRenderer" ||
            spec.direction === "RendererToRenderer" ||
            spec.direction === "MainToUtility" ||
            spec.direction === "UtilityToMain" ||
            spec.direction === "RendererToUtility" ||
            spec.direction === "ServiceWorkerToMain" ||
            spec.direction === "MainToServiceWorker")
      );
   }

   /** Whether any channel of the file goes through the serializer, which the file then imports. */
   protected hasSerializedChannels(): boolean {
      return this.pfsArray.some((pfs) =>
         pfs.specs.channelSpecArray.some((spec) => this.isSerializedSpec(spec)),
      );
   }

   protected getCodeIndents(): string[] {
      return [1, 2, 3, 4, 5, 6].map((value) => {
         return " ".repeat(this.config.codeIndent).repeat(value);
      });
   }

   /**
    * The channel specs of a schema file, with the type names of their signatures replaced by
    * the names that the generated imports declare (see `ImportsGenerator.getRenames`).
    */
   protected getChannelSpecs(parsedFileSpecs: t.ParsedFileSpecs): t.ChannelSpec[] {
      return renameChannelSpecs(
         parsedFileSpecs.specs.channelSpecArray,
         this.importsGenerator.getRenames(parsedFileSpecs),
         (importPath) => this.importsGenerator.getImportTypePath(parsedFileSpecs, importPath),
      );
   }

   /**
    * Inserts the event parameter at the start of the parameter list of the signature.
    * The position comes from the parser, since the first `(` of the text can belong to
    * the type parameters, as in `<T extends (x: number) => void>(cb: T) => void`.
    */
   protected injectEventTypehint(
      signature: t.CallableSignature,
      eventType: string,
      eventName = "event",
   ): string {
      const { definition, paramsStart, params } = signature;
      const separator = params.length > 0 ? ", " : "";
      return [
         definition.slice(0, paramsStart),
         `${eventName}: ${eventType}${separator}`,
         definition.slice(paramsStart),
      ].join("");
   }

   /**
    * Returns the type parameters of the signature, such as `<T extends Foo>`, or an empty
    * string. Generated functions repeat them so that the
    * parameter types which refer to them stay valid.
    */
   protected getTypeParams(signature: t.CallableSignature): string {
      return signature.definition.slice(0, signature.paramsStart - 1).trim();
   }

   /** The parameters of the channel, with their types or only their names (see `resolveParams`). */
   protected getOriginalParams(spec: t.ChannelSpec, onlyNames: boolean): string {
      return getOriginalParams(spec, onlyNames);
   }

   /** The `maxQueue` of a port channel as source text: a number, or `Infinity`. */
   protected getMaxQueue(spec: t.ChannelSpec): string {
      return String(spec.maxQueue ?? DEFAULT_MAX_QUEUE);
   }

   /** The `highWaterMark` of a stream channel as source text: a number, or `Infinity`. */
   protected getHighWaterMark(spec: t.ChannelSpec): string {
      return String(spec.highWaterMark ?? DEFAULT_HIGH_WATER_MARK);
   }

   /**
    * Joins the components of a file, such as the imports, the helpers and the exposed object, with
    * a newline, as `join("\n")` does. A component may start or end with blank lines of its own, so
    * where two components meet, the newlines are capped at one blank line. The text inside a
    * component is kept as it is.
    */
   protected joinComponents(components: string[]): string {
      const [first = "", ...rest] = components;
      let out = first;
      for (const component of rest) {
         const trailing = out.length - out.replace(/\n+$/, "").length;
         const leading = component.length - component.replace(/^\n+/, "").length;
         const newlines = Math.min(trailing + 1 + leading, 2);
         out =
            out.slice(0, out.length - trailing) + "\n".repeat(newlines) + component.slice(leading);
      }
      return out;
   }

   /**
    * Sorts the channels by name, in code unit order, so that the output does not depend on
    * the locale: `getFoo` comes before `getFoo2`, and upper case before lower case.
    */
   protected sortChannels<T extends { name: string }>(channels: T[]): T[] {
      return channels.sort((a, b) => utils.compareStrings(a.name, b.name));
   }

   public async write(withNotice = true) {
      const targetFilePath = this.getTargetFilePath();
      const fileDirectory = path.dirname(targetFilePath);
      await fsp.mkdir(fileDirectory, { recursive: true });
      let contents: string;
      if (this.isEmpty()) {
         contents = this.renderEmptyFileContents();
      } else {
         contents = this.renderFileContents();
      }
      // The file starts with its first line, not with a blank one.
      contents = contents.replace(/^\n+/, "");
      if (withNotice) {
         contents = `${this.notice}\n\n${contents}`;
      }
      await fsp.writeFile(targetFilePath, contents);
   }
}
