/*
 *   Apache License 2.0
 *
 *   Copyright (c) 2024, Mattias Aabmets
 *
 *   The contents of this file are subject to the terms and conditions defined in the License.
 *   You may not use, modify, or distribute this file except in compliance with the License.
 *
 *   SPDX-License-Identifier: Apache-2.0
 */

import fsp from "node:fs/promises";
import path from "node:path";
import type * as t from "@types";
import utils from "../utils.js";
import { ImportsGenerator } from "./imports-generator.js";

/**
 * Replaces the type names of a signature text, such as `User` with `User_2`. Only references
 * are replaced, not the members of a qualified name, string literals, property keys or
 * parameter names.
 */
function renameTypeReferences(text: string, renames: ReadonlyMap<string, string>): string {
   const token = /(["'`])(?:\\.|(?!\1).)*\1|[A-Za-z_$][\w$]*/g;
   return text.replace(token, (match, quote, offset: number) => {
      const renamed = quote ? undefined : renames.get(match);
      if (renamed === undefined) {
         return match;
      }
      const before = text.slice(0, offset);
      const after = text.slice(offset + match.length);
      const isMember = /\.\s*$/.test(before);
      const isKey = /(?:[({,;]|\breadonly)\s*$/.test(before) && /^\s*\??\s*:/.test(after);
      return isMember || isKey ? match : renamed;
   });
}
const IDENTIFIER_PATTERN = /^[A-Za-z_$][\w$]*$/;
const IDENTIFIER_TOKENS = /[A-Za-z_$][\w$]*/g;

export class BaseWriter {
   protected config: t.IPCResolvedConfig;
   protected pfsArray: t.ParsedFileSpecs[];
   protected importsGenerator: ImportsGenerator;
   protected indents: string[];
   protected notice = utils.dedent(`
      // NOTICE: THIS FILE WAS GENERATED BY AUTOMATE-ELECTRON-IPC.
      // ANY CHANGES TO THIS FILE WILL NOT PERSIST BETWEEN GENERATIONS.
   `);

   public constructor(config: t.IPCResolvedConfig, pfsArray: t.ParsedFileSpecs[]) {
      if (this.constructor === BaseWriter) {
         throw new Error(`Cannot instantiate abstract base class '${this.constructor.name}'`);
      }
      this.config = config;
      this.pfsArray = pfsArray;
      this.importsGenerator = new ImportsGenerator(
         config.projectUsesNodeNext,
         this.getTargetFilePath(),
      );
      this.indents = this.getCodeIndents();
   }

   private throwAbstractError(methodName: string): void {
      throw new Error(`Must implement method '${methodName}' in '${this.constructor.name}' class`);
   }

   protected getTargetFilePath(): string {
      this.throwAbstractError("getTargetFilePath");
      return null as unknown as string;
   }

   protected renderEmptyFileContents(): string {
      this.throwAbstractError("renderEmptyFileContents");
      return null as unknown as string;
   }

   protected renderFileContents(): string {
      this.throwAbstractError("generateFileContents");
      return null as unknown as string;
   }

   protected getCodeIndents(): string[] {
      return [1, 2, 3, 4, 5].map((value) => {
         return " ".repeat(this.config.codeIndent).repeat(value);
      });
   }

   /**
    * The channel specs of a schema file, with the type names of their signatures replaced by
    * the names that the generated imports declare (see `ImportsGenerator.getRenames`).
    */
   protected getChannelSpecs(parsedFileSpecs: t.ParsedFileSpecs): t.ChannelSpec[] {
      const specs = parsedFileSpecs.specs.channelSpecArray;
      const renames = this.importsGenerator.getRenames(parsedFileSpecs);
      if (renames.size === 0) {
         return specs;
      }
      return specs.map((spec) => ({
         ...spec,
         signature: {
            ...spec.signature,
            definition: renameTypeReferences(spec.signature.definition, renames),
            returnType: renameTypeReferences(spec.signature.returnType, renames),
            params: spec.signature.params.map((param) => ({
               ...param,
               type: renameTypeReferences(param.type, renames),
            })),
         },
      }));
   }

   protected injectEventTypehint(sigDef: string): string {
      return sigDef.replace("(", "(event: IpcMainEvent, ");
   }

   /**
    * Returns the parameters of the channel signature with names that are valid identifiers.
    * Destructured parameters, such as `{ a, b }: Foo`, cannot be forwarded by name,
    * so they are replaced by generated names that clash with no name in the signature.
    */
   protected resolveParams(spec: t.ChannelSpec): t.CallableParam[] {
      const params = spec.signature.params;
      const taken = this.collectIdentifiers(params.map((param) => param.name));
      return params.map((param, index) => {
         if (IDENTIFIER_PATTERN.test(param.name)) {
            return param;
         }
         return { ...param, name: this.uniqueName(`arg${index}`, taken) };
      });
   }

   protected getOriginalParams(spec: t.ChannelSpec, onlyNames: boolean): string {
      return this.resolveParams(spec)
         .map((param) => {
            const rest = param.rest ? "..." : "";
            if (onlyNames) {
               return `${rest}${param.name}`;
            }
            const optional = param.optional ? "?" : "";
            return `${rest}${param.name}${optional}: ${param.type || "any"}`;
         })
         .join(", ");
   }

   /**
    * Collects every identifier-like token of the given source snippets.
    * Names that are absent from the result cannot clash with anything in the snippets.
    */
   protected collectIdentifiers(snippets: string[]): Set<string> {
      return new Set(snippets.flatMap((snippet) => snippet.match(IDENTIFIER_TOKENS) ?? []));
   }

   /**
    * Returns `base`, with underscores prepended until it is absent from `taken`,
    * and adds the result to `taken`.
    */
   protected uniqueName(base: string, taken: Set<string>): string {
      let name = base;
      while (taken.has(name)) {
         name = `_${name}`;
      }
      taken.add(name);
      return name;
   }

   protected sortCallablesArray(callablesArray: string[]): string[] {
      return callablesArray.sort((a, b) => {
         const prefixOrder = ["on", "send"];
         const getPrefixRank = (value: string) => {
            for (let i = 0; i < prefixOrder.length; i++) {
               if (value.startsWith(prefixOrder[i])) {
                  return i;
               }
            }
            return prefixOrder.length;
         };
         const prefixRankA = getPrefixRank(a);
         const prefixRankB = getPrefixRank(b);
         if (prefixRankA === prefixRankB) {
            return a.localeCompare(b);
         }
         return prefixRankA - prefixRankB;
      });
   }

   public async write(withNotice = true) {
      const targetFilePath = this.getTargetFilePath();
      const fileDirectory = path.dirname(targetFilePath);
      await fsp.mkdir(fileDirectory, { recursive: true });
      let contents: string;
      if (this.pfsArray.length === 0) {
         contents = this.renderEmptyFileContents();
      } else {
         contents = this.renderFileContents();
      }
      if (withNotice) {
         contents = `${this.notice}\n${contents}`;
      }
      await fsp.writeFile(targetFilePath, contents);
   }
}
