/*
 *   Apache License 2.0
 *
 *   Copyright (c) 2024, Mattias Aabmets
 *
 *   The contents of this file are subject to the terms and conditions defined in the License.
 *   You may not use, modify, or distribute this file except in compliance with the License.
 *
 *   SPDX-License-Identifier: Apache-2.0
 */

import { GENERATED_PREFIX, notice } from "@src/output-files.js";
import { fixtures } from "@testutils/fixture-tracker.js";
import type * as t from "@types";
import { describe, expect, it } from "vitest";

const configFor = (schemaPath: string) =>
   ({ projectRoot: "/p", ipcSchema: { path: schemaPath } }) as t.IPCResolvedConfig;

describe("notice", () => {
   it("names the schema file relative to the project root", () => {
      expect(notice(configFor("/p/src/autoipc/schema.ts"))).toStrictEqual(
         [
            "// Generated by ipcgen (automate-electron-ipc) from src/autoipc/schema.ts. Do not edit.",
            "/* eslint-disable */",
            "// biome-ignore-all lint: generated file",
            "// biome-ignore-all assist: generated file",
            "// biome-ignore-all format: generated file",
         ].join("\n"),
      );
   });

   it("names the schema directory of a schema that is split into files", () => {
      expect(notice(configFor("/p/ipc/schema")).split("\n")[0]).toBe(
         "// Generated by ipcgen (automate-electron-ipc) from ipc/schema. Do not edit.",
      );
   });

   it("starts with the prefix that the removal of stale files looks for", () => {
      expect(notice(configFor("/p/ipc/schema.ts")).startsWith(GENERATED_PREFIX)).toBe(true);
   });
});

describe("notice, in the generated files", () => {
   it.each([
      ["single-file", "ipc/schema.ts"],
      ["error-collisions", "ipc/schema"],
   ])("opens a .ts file and a .d.ts file of '%s' with it", async (fixture, schemaPath) => {
      const project = await fixtures.run(fixture);
      const first = `// Generated by ipcgen (automate-electron-ipc) from ${schemaPath}. Do not edit.`;
      for (const name of ["main.ts", "preload.ts", "window.d.ts"] as const) {
         const lines = project.generated[name].split("\n");
         expect(lines.slice(0, 5), name).toStrictEqual([
            first,
            "/* eslint-disable */",
            "// biome-ignore-all lint: generated file",
            "// biome-ignore-all assist: generated file",
            "// biome-ignore-all format: generated file",
         ]);
         expect(lines[5]).toBe("");
      }
   });
});
